### ISSUE TITLE
没搞懂怎么上传的

### ISSUE THREAD

**Issue by 459217974** [picone/CloudMusicUploader#1]
这个不是上传文件吗
为什么看起来是通过上传接口把网易云本来就有的资源给解锁了
是这个意思把,看起来是
不能自己上传文件吗
网易云有时候可以自己做到匹配歌曲文件的,难道是通过MD5识别的,感觉没那么简单
还有就是这api从哪里扒出来的啊,好多神奇的参数.
我想弄个一键上传歌单所有歌曲到云盘的脚本,资源可以去qq音乐下载无损的,毕竟qq音乐版权贼多.

**Comment by wogong** [comment]
同好奇，我也有同样需求，Mac 下的客户端无法上传到云盘，要是有个脚本能批量上传就方便了。

**Comment by picone** [comment]
网易云盘的接口通过md5校验文件是否存在，若存在就不会重复上传文件了。但是这个项目目前还有个问题，失败率较高，目前我也没有这方面需求，所以暂时没开发了。有兴趣的伙伴可以一起讨论~
